version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/srv/penny
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    image: php:7.0-fpm
    volumes:
      - .:/srv/penny
