version: "3"

services:
  nginx:
    image: nginx:1.13.0
    ports:
      - "80:80"
    volumes:
      - ..:/srv/penny
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx:/var/log/nginx
    links:
      - php

  php:
    image: slimek/penny:0.2.0
    volumes:
      - ..:/srv/penny
      - /var/log/penny:/var/log/penny
    links:
      - fluentd
      - mysql

  fluentd:
    image: fluent/fluentd:v0.12-debian
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluent.conf
      - /var/log/fluentd:/fluentd/log

  mysql:
    image: mysql:5.7.18
    ports:
      - "3306:3306"
    volumes:
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nxtomotp
