version: "3"

services:
  nginx:
    image: nginx:1.13.0
    ports:
      - "80:80"
    volumes:
      - ../nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ../nginx/php-fpm:/etc/nginx/conf.d/php-fpm
      - /var/log/nginx:/var/log/nginx
      - ..:/srv/penny
    links:
      - php

  php:
    image: slimek/penny:0.1.0
    volumes:
      - ..:/srv/penny
      - /var/log/penny:/var/log/penny
    links:
      - fluentd

  fluentd:
    image: fluent/fluentd:v0.12-debian
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluent.conf
      - /var/log/fluentd:/fluentd/log
